### PR TITLE
Add optional phone number to customers

### PR DESCRIPTION
**Pull request by laander**
Currently, there's no way to bring phone numbers saved on Firebase users into Stripe when creating a checkout session for a subscription.

This PR adds support for that by retrieving the Firebase auth user and if there is a [phoneNumber](https://firebase.google.com/docs/reference/js/v8/firebase.User#phonenumber) present, it will save it on the stripe customer record. Also added support when using the `syncUsersOnCreate` flag and Firebase users created with phone number authentication.

### CODE REVIEW

**Comment by laander** [comment]
@lemuel-stripe Any news on whether this can/will be merged or not? I can fix the merge conflicts if yes

**Comment by dackers86** [comment]
Hi @laander 

This update looks fine, if you can solve the conflicts then i'll be able to give it a review. Thanks!

**Comment by laander** [comment]
@dackers86 Thank you. Solved conflicts now, please have a look again

**Comment by laander** [comment]
Fixed linting issues now, build should pass if you trigger it again

**Review by dackers86 — APPROVED** [review]

**Pull request merged**
