### PR TITLE
feat(firestore-stripe-subscriptions): add Stripe Tax support

### LINKED ISSUE #203: Add checkout session metadata to one time payments
# Bug report

- Extension name: `firestore-stripe-subscriptions`

## Describe the bug

When I pass metadata with a single payment the same way I pass metadata for a subscription, I would expect the metadata to show up for the Stripe payment. I can see the correct metadata passed to the checkout session document, but it doesn't flow through to the payment document.

## Additional context

I've only quickly skimmed through the code, but it looks like the metadata for one time payments might be getting lost here?
https://github.com/stripe/stripe-firebase-extensions/blob/114d09c6f4d3310acd3cc67702991ad02808047d/firestore-stripe-subscriptions/functions/src/index.ts#L154-L160

### LINKED ISSUE #212: Store the URL of a Checkout Session in addition to the session ID
# Feature request

- Extension name: `firestore-stripe-subscriptions`

## Is your feature request related to a problem? Please describe.

I'd like to manually handle the opening of a browser window when calling `createCheckoutSession`.

## Describe the solution you'd like

I'd like the `createCheckoutSession` function to also store the `session.url` inside Firestore, in addition to the `session.id`, like a manual POST to Stripe would return.
Right now, only the `session.id` is stored, and I have to use that in the client-side with `stripe.redirectToCheckout({ sessionId })`.

## Describe alternatives you've considered

I tried manually building the URL, but of course it doesn't work due to a fragment I don't know anything about (probably some kind of checksum or additional data).

## Additional context

https://github.com/stripe/stripe-firebase-extensions/blob/master/firestore-stripe-subscriptions/functions/src/index.ts#L172-L176

### PR DESCRIPTION
**Pull request by thorsten-stripe**
## Version 0.1.14 - 2021-07-08

[feat] Automatic tax calculation with [Stripe Tax](https://stripe.com/tax) - Closes #206 

Stripe Tax lets you calculate and collect sales tax, VAT, and GST.

1. Request access: https://stripe.com/tax#request-access
2. Set up Stripe Tax in the Dashboard: https://stripe.com/docs/tax/set-up
3. Enable automatic tax calculation when creating your `checkout_sessions` docs:

```js
const docRef = await db
  .collection("customers")
  .doc(currentUser.uid)
  .collection("checkout_sessions")
  .add({
    automatic_tax: true, // Automatically calculate tax based on the customer's address
    tax_id_collection: true, // Collect the customer's tax ID (important for B2B transactions)
    price: "price_1GqIC8HYgolSBA35zoTTN2Zl",
    success_url: window.location.origin,
    cancel_url: window.location.origin,
  });
```

[feat] Redirect to Stripe Checkout via URL instead of Stripe.js - Closes #212

Stripe Checkout now returns a URL which means Stripe.js is no longer needed to redirect to checkout:

```js
const docRef = await db
  .collection("${param:CUSTOMERS_COLLECTION}")
  .doc(currentUser.uid)
  .collection("checkout_sessions")
  .add({
    price: "price_1GqIC8HYgolSBA35zoTTN2Zl",
    success_url: window.location.origin,
    cancel_url: window.location.origin,
  });
// Wait for the CheckoutSession to get attached by the extension
docRef.onSnapshot((snap) => {
  const { error, url } = snap.data();
  if (error) {
    // Show an error to your customer and
    // inspect your Cloud Function logs in the Firebase console.
    alert(`An error occured: ${error.message}`);
  }
  if (url) {
    // We have a Stripe Checkout URL, let's redirect.
    window.location.assign(url);
  }
});
```

[fix] Add checkout session metadata to one time payments -  Fixes #203

### CODE REVIEW

**Comment by hesamalavi** [comment]
Hi @thorsten-stripe , thanks for all you support. Adding metadata to one time payments is possible. I wanted to know how you could access them when creating user roles? for example with recurring payments, stripeRole : premium is visible in the claims object. But not in one time payments.

**Comment by cvoadmin** [comment]
Do you need to do anything besides updating the extension and creating links in the dashboard to make it work?

**Comment by cvoadmin** [comment]
Do you need to do anything besides update the extension and create checkout links in the dashboard to make it work?

**Comment by hesamalavi** [comment]
Hi @cvoadmin thanks for your reply. I don't mind, as long as it works. I would love it if when a user makes a purchase, the metadata added to the product in stripe (refer to image below):
Screen Shot 2021-07-27 at 2 07 37 pm

would be added to firebase, then added to custom claims so that when I run a this function:
`export default async function isUserPremium(): Promise<boolean> {
    await firebase.auth().currentUser?.getIdToken(true);
    const decodedToken = await firebase.auth().currentUser?.getIdTokenResult();
    
    return decodedToken?.claims?.stripeRole ? true : false;
}
`
I could give users who have paid (i.e. have a stripeRole) would be able to access parts of my app that only paid users should have access to.

**Comment by cvoadmin** [comment]
@hesamalavi Sorry, my question was intended for thorsten.

**Comment by hesamalavi** [comment]
Of course, just realised :)

**Pull request merged**
